//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAuto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MalevEntities : DbContext
    {
        public MalevEntities()
            : base("name=MalevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Table_Auto> Table_Auto { get; set; }
        public virtual DbSet<Table_EquipmentsUsed> Table_EquipmentsUsed { get; set; }
        public virtual DbSet<Table_Genders> Table_Genders { get; set; }
        public virtual DbSet<Table_Mastera> Table_Mastera { get; set; }
        public virtual DbSet<Table_NewsEquipment> Table_NewsEquipment { get; set; }
        public virtual DbSet<Table_OrderingServices> Table_OrderingServices { get; set; }
        public virtual DbSet<Table_Orders> Table_Orders { get; set; }
        public virtual DbSet<Table_Owners> Table_Owners { get; set; }
        public virtual DbSet<Table_Pasporta> Table_Pasporta { get; set; }
        public virtual DbSet<Table_Roles> Table_Roles { get; set; }
        public virtual DbSet<Table_VidaRabot> Table_VidaRabot { get; set; }
    }
}
