//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_OrderingServices
    {
        public int idOrderingServices { get; set; }
        public int idOrder { get; set; }
        public int idVidaRaboti { get; set; }
        public int idMaster { get; set; }
        public int idEquipmentUsed { get; set; }
        public int idNewEquipment { get; set; }
    
        public virtual Table_EquipmentsUsed Table_EquipmentsUsed { get; set; }
        public virtual Table_Mastera Table_Mastera { get; set; }
        public virtual Table_NewsEquipment Table_NewsEquipment { get; set; }
        public virtual Table_Orders Table_Orders { get; set; }
        public virtual Table_VidaRabot Table_VidaRabot { get; set; }
    }
}
