//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_EquipmentsUsed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_EquipmentsUsed()
        {
            this.Table_OrderingServices = new HashSet<Table_OrderingServices>();
        }
    
        public int idEquipmentUsed { get; set; }
        public string title { get; set; }
        public System.DateTime dateProduction { get; set; }
        public double costEquipment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_OrderingServices> Table_OrderingServices { get; set; }
    }
}
