//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Auto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Auto()
        {
            this.Table_Orders = new HashSet<Table_Orders>();
        }
    
        public int idAuto { get; set; }
        public string markAuto { get; set; }
        public string regZnak { get; set; }
        public string colorAuto { get; set; }
        public System.DateTime dateRelease { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Orders> Table_Orders { get; set; }
    }
}
