//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Orders()
        {
            this.Table_OrderingServices = new HashSet<Table_OrderingServices>();
        }
    
        public int idOrder { get; set; }
        public int idAuto { get; set; }
        public int idOwner { get; set; }
        public System.DateTime dateEntrance { get; set; }
        public int CostEstimation { get; set; }
        public string CostCroka { get; set; }
    
        public virtual Table_Auto Table_Auto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_OrderingServices> Table_OrderingServices { get; set; }
        public virtual Table_Owners Table_Owners { get; set; }
    }
}
